import { Baloo_Da_2, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/sections/navigation/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const baloo = Baloo_Da_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // যেগুলো লাগবে সেগুলো দাও
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${baloo.className}  antialiased`}>
        <div>
          <Nav />
        </div>
        <div className="bg-green-600 w-full h-[70px]"></div>
        {children}
      </body>
    </html>
  );
}
