import {
  Noto_Sans_Bengali,
  Hind_Siliguri,
  Geist,
  Geist_Mono,
} from "next/font/google";

import "./globals.css";

const HindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"], // যতো ওয়েট লাগবে দিয়ে দে
});

const notoBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"], // যতো ওয়েট লাগবে দিয়ে দে
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pathangan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${HindSiliguri.variable} ${notoBengali.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
